// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6pwnU0isG1MhdyEz5PFSz0NCASNfMoI8',
    appId: '1:39168642996:web:9ebc0c9676d0955f296ce1',
    messagingSenderId: '39168642996',
    projectId: 'moonchat-6ba9a',
    authDomain: 'moonchat-6ba9a.firebaseapp.com',
    storageBucket: 'moonchat-6ba9a.firebasestorage.app',
    measurementId: 'G-95CHEBHG46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApsFVsSWUUzSwRWDunaupBMFwwInveWUk',
    appId: '1:39168642996:android:5c1cc208ee63c556296ce1',
    messagingSenderId: '39168642996',
    projectId: 'moonchat-6ba9a',
    storageBucket: 'moonchat-6ba9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9IjjRgUm6kNYZ8CsPg4OVHHpKSgZE2jU',
    appId: '1:39168642996:ios:9ae8650ddd1ced3c296ce1',
    messagingSenderId: '39168642996',
    projectId: 'moonchat-6ba9a',
    storageBucket: 'moonchat-6ba9a.firebasestorage.app',
    iosBundleId: 'com.example.moonchat',
  );
}
